
services:
  db-users:
    container_name: rusve-db-users
    image: ceteuf/postgres-extended:pg18-alpine-v3 #postgres:15.1
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users

  db-notes:
    container_name: rusve-db-notes
    image: ceteuf/postgres-extended:pg18-alpine-v3 #postgres:15.1
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: notes

  db-utils:
    container_name: rusve-db-utils
    image: ceteuf/postgres-extended:pg18-alpine-v3 #postgres:15.1
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users

